In [1]:
import pandas as pd
import numpy as np

In [2]:
# !pip install kaggle

# import os
# !mkdir -p ~/.kaggle
# !cp kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json

# !kaggle datasets download -d taweilo/wine-quality-dataset-balanced-classification --unzip

In [3]:
df = pd.read_csv('wine_data.csv')
df = df.sample(frac=0.5, random_state=42)
df.head(3)

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
2312            11.1              1.01         0.79            43.9   
16845           11.8              0.83         1.32            43.1   
6105             7.6              0.95         0.03             2.0   

       chlorides  free_sulfur_dioxide  total_sulfur_dioxide  density    pH  \
2312       0.159                235.6                 348.4  1.00204  3.08   
16845      0.176                149.0                 246.9  1.01663  3.08   
6105       0.090                  7.0                  20.0  0.99590  3.20   

       sulphates  alcohol  quality  
2312        1.71     12.3        3  
16845       1.59     11.3        8  
6105        0.56      9.6        5

In [4]:
df.describe()

fixed_acidity  volatile_acidity   citric_acid  residual_sugar  \
count   10500.000000      10500.000000  10500.000000    10500.000000   
mean        9.788286          0.773770      0.790639       31.196433   
std         2.417024          0.364879      0.385853       19.007835   
min         3.900000          0.080000      0.000000        0.600000   
25%         7.500000          0.430000      0.410000        9.600000   
50%         9.900000          0.830000      0.860000       37.600000   
75%        11.800000          1.080000      1.110000       46.800000   
max        15.600000          1.580000      1.570000       65.800000   

          chlorides  free_sulfur_dioxide  total_sulfur_dioxide       density  \
count  10500.000000         10500.000000          10500.000000  10500.000000   
mean       0.199291           129.279467            228.082143      1.009894   
std        0.124785            77.573785             99.855458      0.011993   
min        0.009000             1.000000              6.000000      0.987130   
25%        0.072000            45.000000            149.575000      0.997400   
50%        0.204000           145.000000            238.800000      1.012050   
75%        0.296000           194.500000            310.600000      1.019690   
max        0.550000           289.000000            440.000000      1.038980   

                 pH     sulphates       alcohol       quality  
count  10500.000000  10500.000000  10500.000000  10500.000000  
mean       3.160786      1.018695     11.287349      5.982952  
std        0.170286      0.409883      1.183093      1.990643  
min        2.770000      0.250000      8.400000      3.000000  
25%        3.030000      0.610000     10.400000      4.000000  
50%        3.150000      1.080000     11.300000      6.000000  
75%        3.270000      1.360000     12.200000      8.000000  
max        3.850000      1.980000     14.500000      9.000000

In [5]:
df.isnull().sum()

fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
np.isinf(df).values.any()

np.False_

In [7]:
from sklearn.preprocessing import LabelEncoder

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

lb = LabelEncoder()
y = lb.fit_transform(y)
y

array([0, 5, 2, ..., 1, 2, 4])

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)
X_train

array([[ 8.5  ,  1.11 ,  1.16 , ...,  3.22 ,  1.34 , 12.4  ],
       [ 8.5  ,  1.29 ,  1.15 , ...,  3.81 ,  0.87 , 11.3  ],
       [ 8.2  ,  0.42 ,  0.29 , ...,  3.   ,  0.32 , 12.8  ],
       ...,
       [ 7.8  ,  0.735,  0.08 , ...,  3.24 ,  0.71 ,  9.8  ],
       [11.2  ,  1.45 ,  0.98 , ...,  3.24 ,  1.11 , 11.5  ],
       [ 9.5  ,  0.73 ,  1.09 , ...,  3.31 ,  1.44 , 12.1  ]])

In [9]:
from sklearn.preprocessing import StandardScaler
sc  = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
X_train

array([[-0.53440106,  0.91399531,  0.95456149, ...,  0.35445252,
         0.78373172,  0.93848943],
       [-0.53440106,  1.40733342,  0.92860334, ...,  3.82742993,
        -0.36466134,  0.00801078],
       [-0.65866719, -0.97713411, -1.30379748, ..., -0.940556  ,
        -1.70852556,  1.2768453 ],
       ...,
       [-0.82435536, -0.11379242, -1.84891861, ...,  0.47218057,
        -0.75560366, -1.26082375],
       [ 0.58399409,  1.84585618,  0.4873148 , ...,  0.47218057,
         0.22175214,  0.17718871],
       [-0.12018063, -0.12749625,  0.77285444, ...,  0.88422874,
         1.02807067,  0.68472252]])

In [10]:
# class LinearTrain:
#     def __init__(self, input_dim, output_dim, activation='identity'):
#         self.W = np.random.randn(output_dim, input_dim) * 0.01 #Изменено
#         self.b = np.zeros((output_dim, 1))
#         self.activation = activation

#     def activate(self, x):
#         if self.activation == 'identity':
#             return x
#         elif self.activation == 'relu':
#             return np.maximum(0, x)
#         elif self.activation == 'tanh':
#             return np.tanh(x)

#     def activate_derivative(self, x):
#         if self.activation == 'identity':
#             return np.ones_like(x)
#         elif self.activation == 'relu':
#             return (x > 0).astype(float)
#         elif self.activation == 'tanh':
#             return 1 - np.tanh(x) ** 2

#     def linear_transform(self, x):
#         self.x = x
#         self.y = np.dot(self.W, x) + self.b.reshape(-1,1) #Исправлено
#         return self.activate(self.y)

#     def backward(self, grads, grad_output, layer_index):
#         grad_z = grad_output * self.activate_derivative(self.y)
#         grad_W = np.dot(grad_z, self.x.T)
#         grad_b = np.sum(grad_z, axis=1, keepdims=True)
#         grad_x = np.dot(self.W.T, grad_z)

#         # self.W -= learning_rate * grad_W
#         # self.b -= learning_rate * grad_b

#         grads[f'W{layer_index}'] = grad_W # Используем layer_index для сохранения
#         grads[f'b{layer_index}'] = grad_b

#         return grad_x

In [11]:
class RBFTrain:
    def __init__(self, input_dim, output_dim, sigma=1.0):
        self.W = np.random.randn(output_dim, input_dim) * np.sqrt(2 / input_dim)
        self.b = np.zeros((output_dim, 1))
        self.sigma = sigma

    def forward(self, x):
        self.x = x
        distances = np.sum((x[:, np.newaxis, :] - self.W[np.newaxis, :, :]) ** 2, axis=2)
        kernel = np.exp(-distances / (2 * self.sigma ** 2))
        self.out = kernel + self.b.T
        return self.out

    def backward(self, grad_output, grads, layer_index):
        grad_z = grad_output * self.activate_derivative(self.y)
        grad_W = np.dot(grad_z, self.x.T)
        grad_b = np.sum(grad_z, axis=1, keepdims=True)
        grad_x = np.dot(self.W.T, grad_z)
        return grad_x


In [12]:
# def soft_argmax_cross_entropy(x, y):
#     exp_x = np.exp(x - np.max(x, axis=0, keepdims=True))
#     p = exp_x / np.sum(exp_x, axis=0, keepdims=True)
#     grad_x = (p - y)  # Градиент уже является массивом
#     return -np.sum(y * np.log(p + 1e-9)) / y.shape[0], grad_x

**Adargrad**

In [13]:
# class Adagrad:
#     def __init__(self, lr=0.01, eps=1e-8):
#         self.lr = lr
#         self.eps = eps
#         self.G = None

#     def update(self, params, grads):
#         if self.G is None:
#             self.G = {}
#             for name, value in params.items():
#                 self.G[name] = np.zeros_like(value)

#         updated_params = {}
#         for step in params:
#             self.G[step] += grads[step] ** 2
#             updated_params[step] = params[step] - self.lr * grads[step] / (np.sqrt(self.G[step]) + self.eps)

#         return updated_params

In [14]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, f1_score

def train_models(X_train, y_train, X_test, y_test, layer_configs, epochs=50, lr=0.01):
    print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
    results = {}

    for num_layers in layer_configs:
        layers = [LinearTrain(X_train.shape[0], 10, activation='relu')]
        for _ in range(num_layers - 1):
            layers.append(LinearTrain(10, 10, activation='relu'))
        #layers.append(LinearTrain(10, y_train.shape[0], activation='identity'))
        layers.append(LinearTrain(10, y_train.shape[0] if len(y_train.shape) > 1 else 1, activation='identity'))

        optimizer = Adagrad(lr=lr)
        loss_history = []

        for epoch in range(epochs):
            total_loss = 0

            # Прямой проход
            x = X_train
            for layer in layers:
                x = layer.linear_transform(x)

            loss, grad = soft_argmax_cross_entropy(x, y_train)
            total_loss += loss

            # Обратный проход
            grads = {}
            grad_output = grad
            for i in range(len(layers) - 1, -1, -1):
                grad_output = layers[i].backward(grad_output, grads, i)


            for i, layer in enumerate(layers):
                layer.W, layer.b = optimizer.update({'W': layer.W, 'b': layer.b}, {'W': grads[f'W{i}'], 'b': grads[f'b{i}']}).values()

            loss_history.append(total_loss)

        x = X_test
        for layer in layers:
            x = layer.linear_transform(x)
        preds = np.argmax(x, axis=0)
        true_labels = np.argmax(y_test, axis=0)

        if isinstance(true_labels, np.int64):
            true_labels = np.array([true_labels])
        if isinstance(preds, np.int64):
            preds = np.array([preds])

        acc = accuracy_score(true_labels, preds)
        f1 = f1_score(true_labels, preds, average='weighted')

        results[num_layers] = {'loss_history': loss_history, 'accuracy': acc, 'f1': f1}

    plt.figure(figsize=(10, 6))
    for num_layers, data in results.items():
        plt.plot(data['loss_history'], label=f'{num_layers} слоев')
    plt.xlabel('Эпохи')
    plt.ylabel('Потери')
    plt.legend()
    plt.title('Кривые обучения')
    plt.show()

    return results

class LinearTrain:
    def __init__(self, input_dim, output_dim, activation='identity'):
        self.W = np.random.randn(output_dim, input_dim) * 0.01
        self.b = np.zeros((output_dim, 1))
        self.activation = activation

    def activate(self, x):
        if self.activation == 'identity':
            return x
        elif self.activation == 'relu':
            return np.maximum(0, x)
        elif self.activation == 'tanh':
            return np.tanh(x)

    def activate_derivative(self, x):
        if self.activation == 'identity':
            return np.ones_like(x)
        elif self.activation == 'relu':
            return (x > 0).astype(float)
        elif self.activation == 'tanh':
            return 1 - np.tanh(x) ** 2

    def linear_transform(self, x):
        self.x = x
        self.y = np.dot(self.W, x) + self.b.reshape(-1,1)
        return self.activate(self.y)

    def backward(self, grad_output, grads, layer_index):
        grad_z = grad_output * self.activate_derivative(self.y)
        grad_W = np.dot(grad_z, self.x.T)
        grad_b = np.sum(grad_z, axis=1, keepdims=True)
        grad_x = np.dot(self.W.T, grad_z)

        grads[f'W{layer_index}'] = grad_W
        grads[f'b{layer_index}'] = grad_b

        return grad_x

class Adagrad:
    def __init__(self, lr=0.01, eps=1e-8):
        self.lr = lr
        self.eps = eps
        self.G = {}

    def update(self, params, grads):
        updated_params = {}
        for step, value in params.items():
            if step not in self.G:
                self.G[step] = np.zeros_like(value)
            self.G[step] += grads[step] ** 2
            updated_params[step] = value - self.lr * grads[step] / (np.sqrt(self.G[step]) + self.eps)
        return updated_params

def soft_argmax_cross_entropy(x, y):
    exp_x = np.exp(x - np.max(x, axis=0, keepdims=True))
    p = exp_x / np.sum(exp_x, axis=0, keepdims=True)
    grad_x = (p - y)
    return -np.sum(y * np.log(p + 1e-9)) / y.shape[0], grad_x


In [15]:
X_train = X_train.T
y_train = y_train.T
X_test = X_test.T
y_test = y_test.T


In [16]:
y_train = y_train.reshape(1, -1)
y_test = y_test.reshape(1, -1)

In [17]:
layer_configs = [2, 3]
results = train_models(X_train, y_train, X_test, y_test, layer_configs)
for num_layers, metrics in results.items():
    print(f'Слои: {num_layers} | Accuracy: {metrics["accuracy"]:.4f} | F1-score: {metrics["f1"]:.4f}')


X_train shape: (11, 8400), y_train shape: (1, 8400)


ValueError: operands could not be broadcast together with shapes (10,11) (10,10) (10,11) 